/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package web_protocols_lab_1;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author DeGianMind.0
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
	public Form() {
		initComponents();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    list = new java.awt.List();
    add_butt = new java.awt.Button();
    del_butt = new java.awt.Button();
    sort_butt = new java.awt.Button();
    textField1 = new java.awt.TextField();
    textField2 = new java.awt.TextField();
    label1 = new java.awt.Label();

    jButton1.setText("jButton1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBounds(new java.awt.Rectangle(500, 150, 0, 0));

    list.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    list.setName(""); // NOI18N

    add_butt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    add_butt.setLabel("Добавить");
    add_butt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        add_buttActionPerformed(evt);
      }
    });

    del_butt.setLabel("Удалить");
    del_butt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        del_buttActionPerformed(evt);
      }
    });

    sort_butt.setLabel("Сортировать");
    sort_butt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sort_buttActionPerformed(evt);
      }
    });

    textField1.setText("Значение");

    textField2.setText("Номер узла");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(add_butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(del_butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(sort_butt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(60, 60, 60))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(7, 7, 7)
            .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(add_butt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(46, 46, 46)
            .addComponent(del_butt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(46, 46, 46)
            .addComponent(sort_butt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    list.getAccessibleContext().setAccessibleName("");
    list.getAccessibleContext().setAccessibleDescription("");
    add_butt.getAccessibleContext().setAccessibleDescription("");

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void add_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttActionPerformed
			Clist.addNode(textField1.getText());
			String[] s = Clist.getelem();
			list.removeAll();
			int buff = s.length;
			for (int i = 0; i < buff; i++) {
				list.add(s[i]);
			}
    }//GEN-LAST:event_add_buttActionPerformed

    private void del_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_buttActionPerformed
			int buff = Integer.parseInt(textField2.getText());
			String b = Clist.delNode(buff);
			label1.setText(b);
			String[] s = Clist.getelem();
			list.removeAll();
			buff = s.length;
			for (int i = 0; i < buff; i++) {
				list.add(s[i]);
			}
    }//GEN-LAST:event_del_buttActionPerformed

    private void sort_buttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_buttActionPerformed
			Clist.sort();
			String[] s = Clist.getelem();
			list.removeAll();
			int buff = s.length;
			for (int i = 0; i < buff; i++) {
				list.add(s[i]);
			}
    }//GEN-LAST:event_sort_buttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
			java.awt.EventQueue.invokeLater(
				new Runnable () {
					public void run () {
						new Form().setVisible(true); 
					}
				}
			);
    }
    List Clist = new List();
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Button add_butt;
  private java.awt.Button del_butt;
  private javax.swing.JButton jButton1;
  private java.awt.Label label1;
  private java.awt.List list;
  private java.awt.Button sort_butt;
  private java.awt.TextField textField1;
  private java.awt.TextField textField2;
  // End of variables declaration//GEN-END:variables
}
